import 'package:mobile_app/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:mobile_app/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:mobile_app/ui/views/bottom_nav/bottom_nav_view.dart';
import 'package:mobile_app/ui/views/dashboard/dashboard_view.dart';
import 'package:mobile_app/ui/views/email/email_view.dart';
import 'package:mobile_app/ui/views/goal_save/goal_save_view.dart';
import 'package:mobile_app/ui/views/group_save/group_save_view.dart';
import 'package:mobile_app/ui/views/investment/investment_view.dart';
import 'package:mobile_app/ui/views/lock_save/lock_save_view.dart';
import 'package:mobile_app/ui/views/onboarding/onboarding_view.dart';
import 'package:mobile_app/ui/views/profile/profile_view.dart';
import 'package:mobile_app/ui/views/saving/saving_view.dart';
import 'package:mobile_app/ui/views/verification/verification_view.dart';
import 'package:mobile_app/ui/bottom_sheets/crypto_deposit/crypto_deposit_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/deposit/deposit_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/withdraw/withdraw_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/group_save_selection/group_save_selection_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/send/send_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/crypto_send/crypto_send_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/fiat_send_selection/fiat_send_selection_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/ngn_send/ngn_send_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/crypto_method_selection/crypto_method_selection_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/chain_selection/chain_selection_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/fiat_method_selection/fiat_method_selection_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/card_deposit/card_deposit_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/bank_transfer/bank_transfer_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/virtual_account/virtual_account_sheet.dart';
import 'package:mobile_app/ui/bottom_sheets/language_selection/language_selection_sheet.dart';
import 'package:mobile_app/services/wallet_service.dart';
import 'package:mobile_app/services/auth_service.dart';
import 'package:mobile_app/services/token_service.dart';
import 'package:mobile_app/services/firebase_wallet_manager_service.dart';
import 'package:mobile_app/services/firebase_auth_service.dart';
import 'package:mobile_app/ui/views/auth/auth_view.dart';
import 'package:mobile_app/ui/views/register/register_view.dart';
import 'package:mobile_app/services/api_service.dart';
import 'package:mobile_app/services/contract_service.dart';
import 'package:mobile_app/services/localization_service.dart';
import 'package:mobile_app/ui/views/porket_save/porket_save_view.dart';
import 'package:mobile_app/ui/views/goal_save/create_goal/create_goal_view.dart';
import 'package:mobile_app/ui/views/lock_save/create_lock/create_lock_view.dart';
import 'package:mobile_app/ui/views/create_public_group_save/create_public_group_save_view.dart';
import 'package:mobile_app/ui/views/create_private_group_save/create_private_group_save_view.dart';
import 'package:mobile_app/ui/views/group_save_details/group_save_details_view.dart';
import 'package:mobile_app/ui/views/goal_save_details/goal_save_details_view.dart';
import 'package:mobile_app/ui/views/goal_save_details/goal_save_details_view.dart';
import 'package:mobile_app/ui/views/dashboard/dashboard_viewmodel.dart';
import 'package:mobile_app/ui/views/goal_save/goal_save_viewmodel.dart';
import 'package:mobile_app/ui/views/badges/badges_view.dart';
import 'package:mobile_app/ui/views/login/login_view.dart';
import 'package:mobile_app/ui/views/login/login_view.dart';
import 'package:mobile_app/ui/views/lock_save_details/lock_save_details_view.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: StartupView),
    MaterialRoute(page: BottomNavView),
    MaterialRoute(page: DashboardView),
    MaterialRoute(page: EmailView),
    MaterialRoute(page: GoalSaveView),
    MaterialRoute(page: GroupSaveView),
    MaterialRoute(page: InvestmentView),
    MaterialRoute(page: LockSaveView),
    MaterialRoute(page: OnboardingView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: SavingView),
    MaterialRoute(page: VerificationView),
    MaterialRoute(page: AuthView),
    MaterialRoute(page: RegisterView),
    MaterialRoute(page: PorketSaveView),
    MaterialRoute(page: CreateGoalView),
    MaterialRoute(page: CreateLockView),
    MaterialRoute(page: CreatePublicGroupSaveView),
    MaterialRoute(page: CreatePrivateGroupSaveView),
    MaterialRoute(page: GroupSaveDetailsView),
    MaterialRoute(page: GoalSaveDetailsView),
    MaterialRoute(page: BadgesView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: LockSaveDetailsView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: WalletService),
    LazySingleton(classType: AuthService),
    LazySingleton(classType: TokenService),
    LazySingleton(classType: FirebaseWalletManagerService),
    LazySingleton(classType: FirebaseAuthService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: ApiService),
    LazySingleton(classType: ContractService),
    LazySingleton(classType: LocalizationService),
    LazySingleton(classType: DashboardViewModel),
    LazySingleton(classType: GoalSaveViewModel),
    // @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: CryptoDepositSheet),
    StackedBottomsheet(classType: DepositSheet),
    StackedBottomsheet(classType: WithdrawSheet),
    StackedBottomsheet(classType: GroupSaveSelectionSheet),
    StackedBottomsheet(classType: SendSheet),
    StackedBottomsheet(classType: CryptoSendSheet),
    StackedBottomsheet(classType: FiatSendSelectionSheet),
    StackedBottomsheet(classType: NgnSendSheet),
    StackedBottomsheet(classType: CryptoMethodSelectionSheet),
    StackedBottomsheet(classType: ChainSelectionSheet),
    StackedBottomsheet(classType: FiatMethodSelectionSheet),
    StackedBottomsheet(classType: CardDepositSheet),
    StackedBottomsheet(classType: BankTransferSheet),
    StackedBottomsheet(classType: VirtualAccountSheet),
    StackedBottomsheet(classType: LanguageSelectionSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    // @stacked-dialog
  ],
)
class App {}
